#!/usr/bin/env php
<?php

if (!isset($argv[1])) {
    echo "You need to set domain name, for example: create-nginx-vhost mysite.ru\n";
    echo "Or with specific directory in /var/www/: create-nginx-vhost mysite.ru my_site_dir\n";
    exit(1);
}

$domain = $argv[1];

if (isset($argv[2]) and !empty($argv[2])) {
    $dir = $argv[2];
} else {
    $dir = $domain;
}

if (file_exists('/var/www/' . $dir)) {
    echo "Domain $domain in $dir is exists.\n";
    exit(1);
}

$conf = '
server {
    server_name '.$domain.';
    root /var/www/'.$dir.'/public;
    error_log /var/log/nginx/'.$dir.'_errors.log;
    access_log /var/log/nginx/'.$dir.'_access.log;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    
    # Deny dot files
    location ~ /\.(ht|git) {
        deny all;
    }

    index index.php;

    location ~ \.php$ {
        try_files $uri = 404;
        include php_default;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
';

$robotsTxt = "
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-Agent: *
Disallow: /cgi-bin/
Disallow: /admin/
";

file_put_contents('/etc/nginx/sites-enabled/'.$dir.'.conf', $conf);

mkdir("/var/www/{$dir}");
mkdir("/var/www/{$dir}/public");
file_put_contents("/var/www/{$dir}/public/index.php", $domain . ' is under construction...');
file_put_contents("/var/www/{$dir}/public/robots.txt", $robotsTxt);
system("chown -hR www-data:www-data /var/www/{$dir}/public");

system('/etc/init.d/nginx reload');
